name: Naver Land Bot

on:
  schedule:
    # UTC 기준이므로 한국 시간(KST) 오후 5시 40분은 UTC 오전 8시 40분입니다.
    - cron: '40 8 * * *'
  workflow_dispatch: # 수동 실행 버튼 추가

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: appleboy/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python a.py
